<?php

use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $datas = array(
            array('country'=>'Afghanistan', 'phone_code'=>'93', 'iso_code'=>'AFG'),
            array('country'=>'Albania', 'phone_code'=>'355', 'iso_code'=>'ALB'),
            array('country'=>'Algeria', 'phone_code'=>'213', 'iso_code'=>'DZA'),
            array('country'=>'American Samoa', 'phone_code'=>'1-684', 'iso_code'=>'ASM'),
            array('country'=>'Andorra', 'phone_code'=>'376', 'iso_code'=>'AND'),
            array('country'=>'Angola', 'phone_code'=>'244', 'iso_code'=>'AGO'),
            array('country'=>'Anguilla', 'phone_code'=>'1-264', 'iso_code'=>'AIA'),
            array('country'=>'Antarctica', 'phone_code'=>'672', 'iso_code'=>'ATA'),
            array('country'=>'Antigua and Barbuda', 'phone_code'=>'1-268', 'iso_code'=>'ATG'),
            array('country'=>'Argentina', 'phone_code'=>'54', 'iso_code'=>'ARG'),
            array('country'=>'Armenia', 'phone_code'=>'374', 'iso_code'=>'ARM'),
            array('country'=>'Aruba', 'phone_code'=>'297', 'iso_code'=>'ABW'),
            array('country'=>'Australia', 'phone_code'=>'61', 'iso_code'=>'AUS'),
            array('country'=>'Austria', 'phone_code'=>'43', 'iso_code'=>'AUT'),
            array('country'=>'Azerbaijan', 'phone_code'=>'994', 'iso_code'=>'AZE'),
            array('country'=>'Bahamas', 'phone_code'=>'1-242', 'iso_code'=>'BHS'),
            array('country'=>'Bahrain', 'phone_code'=>'973', 'iso_code'=>'BHR'),
            array('country'=>'Bangladesh', 'phone_code'=>'880', 'iso_code'=>'BGD'),
            array('country'=>'Barbados', 'phone_code'=>'1-246', 'iso_code'=>'BRB'),
            array('country'=>'Belarus', 'phone_code'=>'375', 'iso_code'=>'BLR'),
            array('country'=>'Belgium', 'phone_code'=>'32', 'iso_code'=>'BEL'),
            array('country'=>'Belize', 'phone_code'=>'501', 'iso_code'=>'BLZ'),
            array('country'=>'Benin', 'phone_code'=>'229', 'iso_code'=>'BEN'),
            array('country'=>'Bermuda', 'phone_code'=>'1-441', 'iso_code'=>'BMU'),
            array('country'=>'Bhutan', 'phone_code'=>'975', 'iso_code'=>'BTN'),
            array('country'=>'Bolivia', 'phone_code'=>'591', 'iso_code'=>'BOL'),
            array('country'=>'Bosnia and Herzegovina', 'phone_code'=>'387', 'iso_code'=>'BIH'),
            array('country'=>'Botswana', 'phone_code'=>'267', 'iso_code'=>'BWA'),
            array('country'=>'Brazil', 'phone_code'=>'55', 'iso_code'=>'BRA'),
            array('country'=>'British Indian Ocean Territory', 'phone_code'=>'246', 'iso_code'=>'IOT'),
            array('country'=>'British Virgin Islands', 'phone_code'=>'1-284', 'iso_code'=>'VGB'),
            array('country'=>'Brunei', 'phone_code'=>'673', 'iso_code'=>'BRN'),
            array('country'=>'Bulgaria', 'phone_code'=>'359', 'iso_code'=>'BGR'),
            array('country'=>'Burkina Faso', 'phone_code'=>'226', 'iso_code'=>'BFA'),
            array('country'=>'Burundi', 'phone_code'=>'257', 'iso_code'=>'BDI'),
            array('country'=>'Cambodia', 'phone_code'=>'855', 'iso_code'=>'KHM'),
            array('country'=>'Cameroon', 'phone_code'=>'237', 'iso_code'=>'CMR'),
            array('country'=>'Canada', 'phone_code'=>'1', 'iso_code'=>'CAN'),
            array('country'=>'Cape Verde', 'phone_code'=>'238', 'iso_code'=>'CPV'),
            array('country'=>'Cayman Islands', 'phone_code'=>'1-345', 'iso_code'=>'CYM'),
            array('country'=>'Central African Republic', 'phone_code'=>'236', 'iso_code'=>'CAF'),
            array('country'=>'Chad', 'phone_code'=>'235', 'iso_code'=>'TCD'),
            array('country'=>'Chile', 'phone_code'=>'56', 'iso_code'=>'CHL'),
            array('country'=>'China', 'phone_code'=>'86', 'iso_code'=>'CHN'),
            array('country'=>'Christmas Island', 'phone_code'=>'61', 'iso_code'=>'CXR'),
            array('country'=>'Cocos Islands', 'phone_code'=>'61', 'iso_code'=>'CCK'),
            array('country'=>'Colombia', 'phone_code'=>'57', 'iso_code'=>'COL'),
            array('country'=>'Comoros', 'phone_code'=>'269', 'iso_code'=>'COM'),
            array('country'=>'Cook Islands', 'phone_code'=>'682', 'iso_code'=>'COK'),
            array('country'=>'Costa Rica', 'phone_code'=>'506', 'iso_code'=>'CRI'),
            array('country'=>'Croatia', 'phone_code'=>'385', 'iso_code'=>'HRV'),
            array('country'=>'Cuba', 'phone_code'=>'53', 'iso_code'=>'CUB'),
            array('country'=>'Curacao', 'phone_code'=>'599', 'iso_code'=>'CUW'),
            array('country'=>'Cyprus', 'phone_code'=>'357', 'iso_code'=>'CYP'),
            array('country'=>'Czech Republic', 'phone_code'=>'420', 'iso_code'=>'CZE'),
            array('country'=>'Democratic Republic of the Congo', 'phone_code'=>'243', 'iso_code'=>'COD'),
            array('country'=>'Denmark', 'phone_code'=>'45', 'iso_code'=>'DNK'),
            array('country'=>'Djibouti', 'phone_code'=>'253', 'iso_code'=>'DJI'),
            array('country'=>'Dominica', 'phone_code'=>'1-767', 'iso_code'=>'DMA'),
            array('country'=>'Dominican Republic', 'phone_code'=>'1-809', 'iso_code'=>'DOM'),
            array('country'=>'East Timor', 'phone_code'=>'670', 'iso_code'=>'TLS'),
            array('country'=>'Ecuador', 'phone_code'=>'593', 'iso_code'=>'ECU'),
            array('country'=>'Egypt', 'phone_code'=>'20', 'iso_code'=>'EGY'),
            array('country'=>'El Salvador', 'phone_code'=>'503', 'iso_code'=>' SLV'),
            array('country'=>'Equatorial Guinea', 'phone_code'=>'240', 'iso_code'=>'GNQ'),
            array('country'=>'Eritrea', 'phone_code'=>'291', 'iso_code'=>'ERI'),
            array('country'=>'Estonia', 'phone_code'=>'372', 'iso_code'=>'EST'),
            array('country'=>'Ethiopia', 'phone_code'=>'251', 'iso_code'=>'ETH'),
            array('country'=>'Falkland Islands', 'phone_code'=>'500', 'iso_code'=>'FLK'),
            array('country'=>'Faroe Islands', 'phone_code'=>'298', 'iso_code'=>'FRO'),
            array('country'=>'Fiji', 'phone_code'=>'679', 'iso_code'=>'FJI'),
            array('country'=>'Finland', 'phone_code'=>'358', 'iso_code'=>'FIN'),
            array('country'=>'France', 'phone_code'=>'33', 'iso_code'=>'FRA'),
            array('country'=>'French Polynesia', 'phone_code'=>'689', 'iso_code'=>'PYF'),
            array('country'=>'Gabon', 'phone_code'=>'241', 'iso_code'=>'GAB'),
            array('country'=>'Gambia', 'phone_code'=>'220', 'iso_code'=>'GMB'),
            array('country'=>'Georgia', 'phone_code'=>'995', 'iso_code'=>'GEO'),
            array('country'=>'Germany', 'phone_code'=>'49', 'iso_code'=>'DEU'),
            array('country'=>'Ghana', 'phone_code'=>'233', 'iso_code'=>'GHA'),
            array('country'=>'Gibraltar', 'phone_code'=>'350', 'iso_code'=>'GIB'),
            array('country'=>'Greece', 'phone_code'=>'30', 'iso_code'=>'GRC'),
            array('country'=>'Greenland', 'phone_code'=>'299', 'iso_code'=>'GRL'),
            array('country'=>'Grenada', 'phone_code'=>'1-473', 'iso_code'=>'GRD'),
            array('country'=>'Guam', 'phone_code'=>'1-671', 'iso_code'=>'GUM'),
            array('country'=>'Guatemala', 'phone_code'=>'502', 'iso_code'=>'GTM'),
            array('country'=>'Guernsey', 'phone_code'=>'44-1481', 'iso_code'=>'GGY'),
            array('country'=>'Guinea', 'phone_code'=>'224', 'iso_code'=>'GIN'),
            array('country'=>'Guinea-Bissau', 'phone_code'=>'245', 'iso_code'=>'GNB'),
            array('country'=>'Guyana', 'phone_code'=>'592', 'iso_code'=>'GUY'),
            array('country'=>'Haiti', 'phone_code'=>'509', 'iso_code'=>'HTI'),
            array('country'=>'Honduras', 'phone_code'=>'504', 'iso_code'=>'HND'),
            array('country'=>'Hong Kong', 'phone_code'=>'852', 'iso_code'=>'HKG'),
            array('country'=>'Hungary', 'phone_code'=>'36', 'iso_code'=>'HUN'),
            array('country'=>'Iceland', 'phone_code'=>'354', 'iso_code'=>'ISL'),
            array('country'=>'India', 'phone_code'=>'91', 'iso_code'=>'IND'),
            array('country'=>'Indonesia', 'phone_code'=>'62', 'iso_code'=>'IDN'),
            array('country'=>'Iran', 'phone_code'=>'98', 'iso_code'=>'IRN'),
            array('country'=>'Iraq', 'phone_code'=>'964', 'iso_code'=>'IRQ'),
            array('country'=>'Ireland', 'phone_code'=>'353', 'iso_code'=>'IRL'),
            array('country'=>'Isle of Man', 'phone_code'=>'44-1624', 'iso_code'=>'IMN'),
            array('country'=>'Israel', 'phone_code'=>'972', 'iso_code'=>'ISR'),
            array('country'=>'Italy', 'phone_code'=>'39', 'iso_code'=>'ITA'),
            array('country'=>'Ivory Coast', 'phone_code'=>'225', 'iso_code'=>'CIV'),
            array('country'=>'Jamaica', 'phone_code'=>'1-876', 'iso_code'=>'JAM'),
            array('country'=>'Japan', 'phone_code'=>'81', 'iso_code'=>'JPN'),
            array('country'=>'Jersey', 'phone_code'=>'44-1534', 'iso_code'=>'JEY'),
            array('country'=>'Jordan', 'phone_code'=>'962', 'iso_code'=>'JOR'),
            array('country'=>'Kazakhstan', 'phone_code'=>'7', 'iso_code'=>'KAZ'),
            array('country'=>'Kenya', 'phone_code'=>'254', 'iso_code'=>'KEN'),
            array('country'=>'Kiribati', 'phone_code'=>'686', 'iso_code'=>'KIR'),
            array('country'=>'Kosovo', 'phone_code'=>'383', 'iso_code'=>'XKX'),
            array('country'=>'Kuwait', 'phone_code'=>'965', 'iso_code'=>'KWT'),
            array('country'=>'Kyrgyzstan', 'phone_code'=>'996', 'iso_code'=>'KGZ'),
            array('country'=>'Laos', 'phone_code'=>'856', 'iso_code'=>'LAO'),
            array('country'=>'Latvia', 'phone_code'=>'371', 'iso_code'=>'LVA'),
            array('country'=>'Lebanon', 'phone_code'=>'961', 'iso_code'=>'LBN'),
            array('country'=>'Lesotho', 'phone_code'=>'266', 'iso_code'=>'LSO'),
            array('country'=>'Liberia', 'phone_code'=>'231', 'iso_code'=>'LBR'),
            array('country'=>'Libya', 'phone_code'=>'218', 'iso_code'=>'LBY'),
            array('country'=>'Liechtenstein', 'phone_code'=>'423', 'iso_code'=>'LIE'),
            array('country'=>'Lithuania', 'phone_code'=>'370', 'iso_code'=>'LTU'),
            array('country'=>'Luxembourg', 'phone_code'=>'352', 'iso_code'=>'LUX'),
            array('country'=>'Macau', 'phone_code'=>'853', 'iso_code'=>'MAC'),
            array('country'=>'Macedonia', 'phone_code'=>'389', 'iso_code'=>'MKD'),
            array('country'=>'Madagascar', 'phone_code'=>'261', 'iso_code'=>'MDG'),
            array('country'=>'Malawi', 'phone_code'=>'265', 'iso_code'=>'MWI'),
            array('country'=>'Malaysia', 'phone_code'=>'60', 'iso_code'=>'MYS'),
            array('country'=>'Maldives', 'phone_code'=>'960', 'iso_code'=>'MDV'),
            array('country'=>'Mali', 'phone_code'=>'223', 'iso_code'=>'MLI'),
            array('country'=>'Malta', 'phone_code'=>'356', 'iso_code'=>'MLT'),
            array('country'=>'Marshall Islands', 'phone_code'=>'692', 'iso_code'=>'MHL'),
            array('country'=>'Mauritania', 'phone_code'=>'222', 'iso_code'=>'MRT'),
            array('country'=>'Mauritius', 'phone_code'=>'230', 'iso_code'=>'MUS'),
            array('country'=>'Mayotte', 'phone_code'=>'262', 'iso_code'=>'MYT'),
            array('country'=>'Mexico', 'phone_code'=>'52', 'iso_code'=>'MEX'),
            array('country'=>'Micronesia', 'phone_code'=>'691', 'iso_code'=>'FSM'),
            array('country'=>'Moldova', 'phone_code'=>'373', 'iso_code'=>'MDA'),
            array('country'=>'Monaco', 'phone_code'=>'377', 'iso_code'=>'MCO'),
            array('country'=>'Mongolia', 'phone_code'=>'976', 'iso_code'=>'MNG'),
            array('country'=>'Montenegro', 'phone_code'=>'382', 'iso_code'=>'MNE'),
            array('country'=>'Montserrat', 'phone_code'=>'1-664', 'iso_code'=>'MSR'),
            array('country'=>'Morocco', 'phone_code'=>'212', 'iso_code'=>'MAR'),
            array('country'=>'Mozambique', 'phone_code'=>'258', 'iso_code'=>'MOZ'),
            array('country'=>'Myanmar', 'phone_code'=>'95', 'iso_code'=>'MMR'),
            array('country'=>'Namibia', 'phone_code'=>'264', 'iso_code'=>'NAM'),
            array('country'=>'Nauru', 'phone_code'=>'674', 'iso_code'=>'NRU'),
            array('country'=>'Nepal', 'phone_code'=>'977', 'iso_code'=>'NPL'),
            array('country'=>'Netherlands', 'phone_code'=>'31', 'iso_code'=>'NLD'),
            array('country'=>'Netherlands Antilles', 'phone_code'=>'599', 'iso_code'=>'ANT'),
            array('country'=>'New Caledonia', 'phone_code'=>'687', 'iso_code'=>'NCL'),
            array('country'=>'New Zealand', 'phone_code'=>'64', 'iso_code'=>'NZL'),
            array('country'=>'Nicaragua', 'phone_code'=>'505', 'iso_code'=>'NIC'),
            array('country'=>'Niger', 'phone_code'=>'227', 'iso_code'=>'NER'),
            array('country'=>'Nigeria', 'phone_code'=>'234', 'iso_code'=>'NGA'),
            array('country'=>'Niue', 'phone_code'=>'683', 'iso_code'=>'NIU'),
            array('country'=>'North Korea', 'phone_code'=>'850', 'iso_code'=>'PRK'),
            array('country'=>'Northern Mariana Islands', 'phone_code'=>'1-670', 'iso_code'=>'MNP'),
            array('country'=>'Norway', 'phone_code'=>'Norway', 'iso_code'=>'NOR'),
            array('country'=>'Oman', 'phone_code'=>'968', 'iso_code'=>'OMN'),
            array('country'=>'Pakistan', 'phone_code'=>'92', 'iso_code'=>'PAK'),
            array('country'=>'Palau', 'phone_code'=>'680', 'iso_code'=>'PLW'),
            array('country'=>'Palestine', 'phone_code'=>'970', 'iso_code'=>'PSE'),
            array('country'=>'Panama', 'phone_code'=>'507', 'iso_code'=>'PAN'),
            array('country'=>'Papua New Guinea', 'phone_code'=>'675', 'iso_code'=>'PNG'),
            array('country'=>'Paraguay', 'phone_code'=>'595', 'iso_code'=>'PRY'),
            array('country'=>'Peru', 'phone_code'=>'51', 'iso_code'=>'PER'),
            array('country'=>'Philippines', 'phone_code'=>'63', 'iso_code'=>'PHL'),
            array('country'=>'Pitcairn', 'phone_code'=>'64', 'iso_code'=>'PCN'),
            array('country'=>'Poland', 'phone_code'=>'48', 'iso_code'=>'POL'),
            array('country'=>'Portugal', 'phone_code'=>'351', 'iso_code'=>'PRT'),
            array('country'=>'Puerto Rico', 'phone_code'=>'1-787', 'iso_code'=>'PRI'),
            array('country'=>'Qatar', 'phone_code'=>'974', 'iso_code'=>'QAT'),
            array('country'=>'Republic of the Congo', 'phone_code'=>'242', 'iso_code'=>'COG'),
            array('country'=>'Reunion', 'phone_code'=>'262', 'iso_code'=>'REU'),
            array('country'=>'Romania', 'phone_code'=>'40', 'iso_code'=>'ROU'),
            array('country'=>'Russia', 'phone_code'=>'7', 'iso_code'=>'RUS'),
            array('country'=>'Rwanda', 'phone_code'=>'250', 'iso_code'=>'RWA'),
            array('country'=>'Saint Barthelemy', 'phone_code'=>'590', 'iso_code'=>'BLM'),
            array('country'=>'Saint Helena', 'phone_code'=>'290', 'iso_code'=>'SHN'),
            array('country'=>'Saint Kitts and Nevis', 'phone_code'=>'1-869', 'iso_code'=>'KNA'),
            array('country'=>'Saint Lucia', 'phone_code'=>'1-758', 'iso_code'=>'LCA'),
            array('country'=>'Saint Martin', 'phone_code'=>'590', 'iso_code'=>'MAF'),
            array('country'=>'Saint Pierre and Miquelon', 'phone_code'=>'508', 'iso_code'=>'SPM'),
            array('country'=>'Saint Vincent and the Grenadines', 'phone_code'=>'1-784', 'iso_code'=>'VCT'),
            array('country'=>'Samoa', 'phone_code'=>'685', 'iso_code'=>'WSM'),
            array('country'=>'San Marino', 'phone_code'=>'378', 'iso_code'=>'SMR'),
            array('country'=>'Sao Tome and Principe', 'phone_code'=>'239', 'iso_code'=>'STP'),
            array('country'=>'Saudi Arabia', 'phone_code'=>'966', 'iso_code'=>'SAU'),
            array('country'=>'Senegal', 'phone_code'=>'221', 'iso_code'=>'SEN'),
            array('country'=>'Serbia', 'phone_code'=>'381', 'iso_code'=>'SRB'),
            array('country'=>'Seychelles', 'phone_code'=>'248', 'iso_code'=>'SYC'),
            array('country'=>'Sierra Leone', 'phone_code'=>'232', 'iso_code'=>'SLE'),
            array('country'=>'Singapore', 'phone_code'=>'65', 'iso_code'=>'SGP'),
            array('country'=>'Sint Maarten', 'phone_code'=>'1-721', 'iso_code'=>'SXM'),
            array('country'=>'Slovakia', 'phone_code'=>'421', 'iso_code'=>'SVK'),
            array('country'=>'Slovenia', 'phone_code'=>'386', 'iso_code'=>'SVN'),
            array('country'=>'Solomon Islands', 'phone_code'=>'677', 'iso_code'=>'SLB'),
            array('country'=>'Somalia', 'phone_code'=>'252', 'iso_code'=>'SOM'),
            array('country'=>'South Africa', 'phone_code'=>'27', 'iso_code'=>'ZAF'),
            array('country'=>'South Korea', 'phone_code'=>'82', 'iso_code'=>'KOR'),
            array('country'=>'South Sudan', 'phone_code'=>'211', 'iso_code'=>'SSD'),
            array('country'=>'Spain', 'phone_code'=>'34', 'iso_code'=>'ESP'),
            array('country'=>'Sri Lanka', 'phone_code'=>'94', 'iso_code'=>'LKA'),
            array('country'=>'Sudan', 'phone_code'=>'249', 'iso_code'=>'SDN'),
            array('country'=>'Suriname', 'phone_code'=>'597', 'iso_code'=>'SUR'),
            array('country'=>'Svalbard and Jan Mayen', 'phone_code'=>'47', 'iso_code'=>'SJM'),
            array('country'=>'Swaziland', 'phone_code'=>'268', 'iso_code'=>'SWZ'),
            array('country'=>'Sweden', 'phone_code'=>'46', 'iso_code'=>'SWE'),
            array('country'=>'Switzerland', 'phone_code'=>'41', 'iso_code'=>'CHE'),
            array('country'=>'Syria', 'phone_code'=>'963', 'iso_code'=>'SYR'),
            array('country'=>'Taiwan', 'phone_code'=>'886', 'iso_code'=>'TWN'),
            array('country'=>'Tajikistan', 'phone_code'=>'992', 'iso_code'=>'TJK'),
            array('country'=>'Tanzania', 'phone_code'=>'255', 'iso_code'=>'TZA'),
            array('country'=>'Thailand', 'phone_code'=>'66', 'iso_code'=>'THA'),
            array('country'=>'Togo', 'phone_code'=>'228', 'iso_code'=>'TGO'),
            array('country'=>'Tokelau', 'phone_code'=>'690', 'iso_code'=>'TKL'),
            array('country'=>'Tonga', 'phone_code'=>'676', 'iso_code'=>'TON'),
            array('country'=>'Trinidad and Tobago', 'phone_code'=>'1-868', 'iso_code'=>'TTO'),
            array('country'=>'Tunisia', 'phone_code'=>'216', 'iso_code'=>'TUN'),
            array('country'=>'Turkey', 'phone_code'=>'90', 'iso_code'=>'TUR'),
            array('country'=>'Turkmenistan', 'phone_code'=>'993', 'iso_code'=>'TKM'),
            array('country'=>'Turks and Caicos Islands', 'phone_code'=>'1-649', 'iso_code'=>'TCA'),
            array('country'=>'Tuvalu', 'phone_code'=>'688', 'iso_code'=>'TUV'),
            array('country'=>'U.S. Virgin Islands', 'phone_code'=>'1-340', 'iso_code'=>'VIR'),
            array('country'=>'Uganda', 'phone_code'=>'256', 'iso_code'=>'UGA'),
            array('country'=>'Ukraine', 'phone_code'=>'380', 'iso_code'=>'UKR'),
            array('country'=>'United Arab Emirates', 'phone_code'=>'971', 'iso_code'=>'ARE'),
            array('country'=>'United Kingdom', 'phone_code'=>'44', 'iso_code'=>'GBR'),
            array('country'=>'United States', 'phone_code'=>'1', 'iso_code'=>'USA'),
            array('country'=>'Uruguay', 'phone_code'=>'598', 'iso_code'=>'URY'),
            array('country'=>'Uzbekistan', 'phone_code'=>'998', 'iso_code'=>'UZB'),
            array('country'=>'Vanuatu', 'phone_code'=>'678', 'iso_code'=>'VUT'),
            array('country'=>'Vatican', 'phone_code'=>'379', 'iso_code'=>'VAT'),
            array('country'=>'Vietnam', 'phone_code'=>'84', 'iso_code'=>'VNM'),
            array('country'=>'Wallis and Futuna', 'phone_code'=>'681', 'iso_code'=>'WLF'),
            array('country'=>'Western Sahara', 'phone_code'=>'212', 'iso_code'=>'ESH'),
            array('country'=>'Yemen', 'phone_code'=>'967', 'iso_code'=>'YEM'),
            array('country'=>'Zambia', 'phone_code'=>'260', 'iso_code'=>'ZMB'),
            array('country'=>'Zimbabwe', 'phone_code'=>'263', 'iso_code'=>'ZWE'),

        );

        foreach ($datas as $val) {
            DB::table('countries')->insert([
                'name' => $val['country'],
                'phone_code' => $val['phone_code'],
                'iso_code' => $val['iso_code'],
                'created_at' => now()
            ]);
        }
    }
}
